### ISSUE TITLE
Generating Path Heatmaps

### ISSUE THREAD

**Issue by diazdc** [theislab/graph_abstraction#4]
![download](https://user-images.githubusercontent.com/32173539/32704540-8860b5ca-c7cc-11e7-9d93-ef8fd2bbf047.png)

As shown in your example scripts, I would like to create a simple heatmap depicting the changes in expression between marker genes in clusters 1, 6, 7 and 4 in my attached figure. However, it's not clear to me how you generated these heatmaps using the scanpy package alone.

Based on the paul15 and nestorowa16 example, I can see that pseudotime values are added to the  adata object before the the plot is made, but I can't see where these values were generated in the code. Is there a built in function in scanpy to generate pseudotime values, or were the values generated using another package?  

Just to be clear, I used the pbmc3k example as a model for my script because I'm working with data from 10x. Perhaps I followed the wrong script as an example? Is there a call that the pbmc3k example omits that allows one to generate these heatmaps? Thank you for your time.

**Comment by falexwolf** [comment]
Sorry for the late response!

I see the problem, it's not very clearly documented. You need to add a "root" cell to the AnnData object, like here for example, in the Nestorowa example
```
adata.add['iroot'] = np.flatnonzero(adata.smp['exp_groups'] == 'Stem')[0]
```

I added this on the top of the docs, so that others don't have to wonder about the same thing:
https://scanpy.readthedocs.io/en/latest/api/scanpy.api.tl.aga.html

Tomorrow, there will be a new release (0.3) of Scanpy with a much improved implementation of AGA. 

Pseudotime is done within Scanpy - the pseudotime within AGA is an extension of DPT, which was one of Scanpy's first features.

Cheers,
  Alex

**Comment by diazdc** [comment]
Thanks!
